name: main

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'The package to build'
        required: true
      build_only:
        description: 'Skip deployment (if non-empty)'
        required: false

env:
  PACKAGE_TO_BUILD: "${{github.event.inputs.package}}"
  BUILD_ONLY: "${{github.event.inputs.build_only}}"
  GPG_OPTIONS: "--batch --yes --no-tty --list-options no-show-photos --verify-options no-show-photos --pinentry-mode loopback"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Mount MSYS on A:/
        shell: cmd
        run: |
          subst A: C:\msys64
          A:\usr\bin\bash -lc "which bash"
          A:\usr\bin\echo %PATH%
          
      - name: Export PATH
        run: |
          [Environment]::SetEnvironmentVariable("Path", "A:\usr\bin;"+$env:Path, "Machine")
      - name: Mount MSYS on A:/
        shell: cmd
        run: |
         A:\usr\bin\echo %PATH%
      - name: Test PATH
        shell: cmd
        run: ls /d

          
      - name: Hello
        run: |
          A:/usr/bin/bash -lc "echo Hello world"
